name : FRONT_DEV_DEPLOY

on:
  push:
    branches:
      - main
jobs:
  SSH:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      

      - uses: actions/checkout@v2
      - name: Stop server
        uses: appleboy/ssh-action@master
        with:
          key: ${{ secrets.DEV_SSH_KEY }}
          host: ${{ secrets.FRONT_DEV_HOST }}
          username: ${{ secrets.USER }}
          script: |
            cd bootcampchat
            
            echo "backend-sever 중지 중..."
            pm2 stop frontend-server
            pm2 delete frontend-server

      - name: git clone
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.FRONT_DEV_HOST}}
          username: ${{ secrets.USER}}
          key: ${{ secrets.DEV_SSH_KEY}}

          script: |
            whoami
            cd bootcampchat
            git reset --hard
            git fetch
            git pull
            
      - name: Server runs on BackGround
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.FRONT_DEV_HOST}}
          username: ${{ secrets.USER}}
          key: ${{ secrets.DEV_SSH_KEY}}
          script: |
            echo "프론트 서버를 시작합니다... (모드: $MODE)"
            cd 
            cd bootcampchat/frontend
            NODE_ENV=$MODE pm2 start --name frontend-server npm start \
              --log "./logs/frontend.log" \
              --error "./logs/frontend-error.log"
            cd ..

